project:
  type: book
  output-dir: docs

lang: kr

book:
  title: "gpt-shell"
  author:
    - name: "이광춘"
      affiliations: "사단법인 한국 R 사용자회"
    - name: "신종화"
      affiliations: "사단법인 한국 R 사용자회"
  date: last-modified
  date-format: "YYYY년 MM월 DD일"
  chapters:
    - index.qmd
    # - 00_setup.qmd
    # - 01_openAI.qmd
    # - shell-intro.qmd
    # - shell-filedir.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    cover-image: images/koRea_logo.png
    number-depth: 3
    number-sections: true
    colorlinks: true
    cite-method: biblatex
    code-overflow: wrap
  pdf:
    documentclass: scrreprt


bibliography: bibliography.bib
link-citations: yes
mainfont: "NanumMyeongjo"
sansfont: "NanumGothic"
monofont: "D2Coding"
