project:
  type: book
  output-dir: docs
  preview:
    port: 7777
    browser: false

lang: kr

book:
  title: "gpt-shell"
  author:
    - name: "이광춘"
      affiliations: "사단법인 한국 R 사용자회"
    - name: "신종화"
      affiliations: "사단법인 한국 R 사용자회"
  date: last-modified
  date-format: "YYYY년 MM월 DD일"
  chapters:
    - index.qmd
    - part: "환경설정"
      chapters:
        - 00_setup.qmd
        - 01_openAI.qmd
    - part: "쉘 프로그래밍"
      chapters:
        - 01-shell-intro.qmd
        - 02-shell-filedir.qmd
        - 03-shell-create.qmd
        - 04-shell-pipefilter.qmd
        - 05-shell-loop.qmd
        - 06-shell-script.qmd
        - 07-shell-find.qmd
    - part: "GPT 데이터 과학"
    - references.qmd

format:
  html:
    theme: cosmo
    cover-image: images/koRea_logo.png
    number-depth: 3
    number-sections: true
    colorlinks: true
    cite-method: biblatex
    code-overflow: wrap
  pdf:
    documentclass: scrreprt


bibliography: bibliography.bib
link-citations: yes
mainfont: "NanumMyeongjo"
sansfont: "NanumGothic"
monofont: "D2Coding"


engine: knitr
