---
engine: knitr
---

```{r init, include=FALSE}
#| eval: false
#| echo: false
#| results: asis

source(here::here("_extensions", "bit2r", "bitPublish", "init_environments.R"))

titlebox_block("bitPublish가 제공하는 기능을 이해하고, bitPublish을 이용해서 원하는 
책을 저작할 수 있다.", title = "학습목표", theme = "bluejeans")
```



# 서문 {.unnumbered}

한국 R 사용자회는 기존 수년동안 블로그 형태로 저작된 데이터 과학 관련 저작물을 2022년 쿼토(Quarto) 전자책 기능에 도입하여 디지털 글쓰기의 한 사례로 다양한 전자책을 공개했다.\footnote{https://r2bit.com/book.html} 데이터 과학 글쓰기를 확장한 디지털 글쓰기와 출판은 전혀 다른 개념이라 특히 한국어 특징을 반영한 출판 도구가 전무한 상황에서 한국 R 사용자회가 주도되어 [`bitPublish`](https://github.com/bit2r/bitPublish) 패키지를 지속 개발하고 있다. 또한, 한국 R 사용자회를 사단법인에서 공익법인으로 전환하는 과정에서 출판사 신고증도 획득하면서 챗GPT 디지털 글쓰기를 출판할 수 있는 든든한 토양을 마련했다. 

이를 바탕으로 챗GPT 시대 데이터 과학 자동화 필수도구인 유닉스 쉘(Unix Shell)을 소개하는 "챗GPT 유닉스 쉘"을 출판하게 되었다. 
챗GPT 유닉스 쉘은 카펜트리 재단이 주도하는 과학기술과 공학분야에서 연구를 수행하는 학생, 연구원, 및 전문가들을 대상으로 컴퓨팅 기술을 교육하는 검증된 콘텐츠를 바탕으로 실제 한국에서 소프트웨어 카펜트리 워크샵을 10여 차례 진행한 전문가가 번역한 콘텐츠에 
챗GPT를 유닉스 쉘 프로그래밍에 활용하는 방식을 제시하고 있다. 유닉스 쉘이 다양한 분야에 활용되고 있지만 데이터 과학 분야로 범위를 좁혀 데이터 분석가와 과학자의 생산성을 높히고 신속히 핵심적인 사항을 데이터에서 찾아내고 대용량 데이터도 거침없이 다양한 분석업무를 진행하는데 든든한 도구가 되도록 별도로 구성하여 사례와 코드를 함께 제시하고 있다.


챗GPT 유닉스 쉘은 기존 개발자가 매뉴얼과 구글이나 네이버 검색을 통해 당면한 문제를 해결하는 방식을 넘어 기계(AI)와 함께 
문제 해결은 기본이고 대화형 쉘 프로그래밍을 통해 한단계 더 나아가는 방식도 제시하고 있다. 이 책은 챗GPT 유닉스 쉘의 기본적인 사용법과 다양한 예제를 통해 과학기술 분야에서 데이터를 효율적으로 관리하고 활용하는 방법을 전달합니다. 챗GPT 유닉스 쉘 설치, 구성, 기능, 명령어, 스크립팅, 디버깅 등에 대해 자세히 설명하고 있어, 유닉스 쉘에 익숙하지 않은 초보자부터 유닉스 쉘을 더 깊이 이해하고 싶은 고급 사용자까지 모두에게 유용한 내용을 제공한다. 이 책을 통해 유닉스 쉘의 강력한 기능과 장점을 발견하고, 챗GPT와 유닉스 쉘을 데이터 과학 분야에 접목한 경험을 바탕으로 인공지능과 함께 하는 세상을 미리 경험해 보게 됩니다.


------------

다가오는 새로운 시대에 우리는 선구자가 되어야 합니다. 데이터 과학, 인공지능, 기계학습 등 미래 지향적인 기술은 우리의 생활에서 빠르게 중요한 역할을 하고 있으며, 우리는 이러한 변화에 맞추어 가야 합니다. 이에 따라, 한국 R 사용자회는 이러한 변화의 바람을 선도하고자, 다양한 노력을 지속하고 있습니다.

2022년, 한국 R 사용자회는 쿼토(Quarto) 전자책 기능을 활용하여, 우리의 데이터 과학 관련 저작물들을 한국어로 공개하였습니다. 이들 저작물은 블로그 형태에서 전자책 형태로 재구성되었고, 디지털 글쓰기의 한 사례로서, 데이터 과학을 보다 쉽고 재미있게 배울 수 있는 훌륭한 자료가 되었습니다. 한국 R 사용자회는 이러한 움직임을 통해 데이터 과학 글쓰기의 새로운 지평을 열었으며, 한국어 특성을 반영한 출판 도구의 부재를 극복하고자 노력하였습니다. 이러한 노력의 일환으로, 우리는 bitPublish 패키지를 개발하고 있습니다.

우리의 노력은 한층 더 나아갔습니다. 한국 R 사용자회는 사단법인에서 공익법인으로 전환하는 과정에서 출판사 신고증을 획득하였습니다. 이로 인해, 챗GPT 디지털 글쓰기를 출판할 수 있는 강력한 기반을 마련하였습니다.

이러한 배경을 바탕으로, 저희는 챗GPT 시대에 필수적인 데이터 과학 자동화 도구인 "챗GPT 유닉스 쉘"을 출판하게 되었습니다. 이 책은 데이터 과학 분야에서 유닉스 쉘의 중요성을 강조하며, 실제 데이터 분석가와 과학자가 데이터 분석에서 유닉스 쉘을 어떻게 활용할 수 있는지에 대한 가이드라인을 제공합니다. 이를 위해, 이 책은 기본적인 사용법부터 복잡한 스크립팅과 디버깅에 이르기까지, 다양한 예제를 통해 유닉스 쉘의 모든 것을 깊이 이해할 수 있도록 구성되었습니다.

더 나아가, 이 책은 챗GPT를 유닉스 쉘 프로그래밍에 활용하는 방식을 제시하여, 이론뿐만 아니라 실제 응용에 대한 이해를 돕습니다. 기존에는 매뉴얼이나 검색 엔진을 통해 문제를 해결하던 방식을 넘어, 이 책은 기계(AI)와 함께 문제를 해결하는 새로운 방식을 제시합니다.

따라서 이 책은 초보자부터 고급 사용자까지, 모든 유닉스 쉘 사용자에게 매우 유용한 정보를 제공합니다. 우리의 책 "챗GPT 유닉스 쉘"을 통해, 여러분들은 유닉스 쉘의 강력한 기능과 장점을 발견하고, 챗GPT와 유닉스 쉘을 데이터 과학 분야에 접목한 경험을 바탕으로, 인공지능과 함께하는 새로운 세상을 미리 경험하게 될 것입니다. 이 책이 여러분의 학습과 성장에 큰 도움이 되길 바라며, 풍요로운 데이터 과학 세상을 함께 만들어가는 파트너가 되기를 희망합니다.
